-- QUESTION
INSERT INTO `question` (`id`, `label`, `category`, `subcategory`, `points`, `correct_answer`)
VALUES
    (1,'Did you open the door?','java','spring',1,'tension'),
    (2,'Do you think Tom will come?','java','spring',1,'engineering'),
    (3,'How big an idiot do you think I am?','java','spring',1,'farmer'),
    (4,'Is football a sport?','java','spring',1,'virus'),
    (5,'What\'s the deal with Tom?','java','spring',1,'contract'),
	(6,'If you could meet anyone, who would it be?','java','spring',1,'impression'),
	(7,'What do you want to do when you grow up?','java','spring',1,'dirt'),
	(8,'Have you spoken to him?','java','spring',1,'salad'),
	(9,'What was the big announcement?','java','spring',1,'procedure'),
	(10,'Why me?','java','spring',1,'bedroom'),
	(11,'Do you think you are a bigger man than him?','java','spring',1,'region'),
    (12,'Are you ready for your big date?','java','spring',1,'volume'),
    (13,'Do you deliver to this address?','java','spring',1,'chocolate'),
    (14,'Does she drink coffee?','java','spring',1,'conversation'),
    (15,'What is new with you?','java','spring',1,'poet'),
	(16,'It is quite a big deal, is it not?','java','spring',1,'importance'),
	(17,'Who wrote Treasure Island?','java','spring',1,'cancer'),
	(18,'Where did you see him?','java','spring',1,'reaction'),
	(19,'Could I ask you to do me a big favor?','java','spring',1,'variation'),
	(20,'Which is deeper, a lake or an ocean?','java','spring',1,'cheek'),
	(21,'Have you opened the door?','java','hibernate',1,'tension'),
	(22,'What is wrong with my shirt?','java','hibernate',1,'engineering'),
	(23,'Would you say slowly, please?','java','hibernate',1,'farmer'),
	(24,'What is your address?','java','hibernate',1,'virus'),
    (25,'Could this be the start of something big?','java','hibernate',1,'contract'),
    (26,'What do you see?','java','hibernate',1,'impression'),
    (27,'Is he yours?','java','hibernate',1,'dirt'),
    (28,'That was a big surprise, was it not?','java','hibernate',1,'salad'),
	(29,'What did he tell you?','java','hibernate',1,'procedure'),
	(30,'If you could meet anyone, who would it be?','java','hibernate',1,'bedroom'),
	(31,'Did you say the plant turned purple?','java','hibernate',1,'region'),
	(32,'Did you get that?','java','hibernate',1,'volume'),
	(33,'What are you talking about?','java','hibernate',1,'chocolate'),
	(34,'What is your favorite ice cream flavor?','java','hibernate',1,'conversation'),
    (35,'What is your favorite thing about school?','java','hibernate',1,'poet'),
	(36,'who will do all the housework?','java','hibernate',1,'importance'),
	(37,'What is that huge building in front of us?','java','hibernate',1,'cancer'),
	(38,'Are you ready for your big day?','java','hibernate',1,'reaction'),
	(39,'Where is the President right now?','java','hibernate',1,'variation'),
	(40,'Do you have any hidden talents?','java','hibernate',1,'cheek'),
	(41,'What kind of music do you like to listen to?','java','jsp',1,'tension'),
	(42,'Do you think this is too big?','java','jsp',1,'engineering'),
	(43,'May I come in?','java','jsp',1,'farmer'),
	(44,'Could you spell it?','java','jsp',1,'virus'),
	(45,'What was the big announcement?','java','jsp',1,'contract'),
	(46,'What is the matter?','java','jsp',1,'impression'),
	(47,'Are you all right?','java','jsp',1,'dirt'),
	(48,'How much did your lunch cost?','java','jsp',1,'salad'),
	(49,'Why dont we go dancing?','java','jsp',1,'procedure'),
	(50,'Do you think Tom will come?','java','jsp',1,'bedroom'),
	(51,'We are just one big, happy family, are we not?','java','jsp',1,'region'),
	(52,'Does she live in Paris?','java','jsp',1,'volume'),
	(53,'What do you do for Valentines Day?','java','jsp',1,'chocolate'),
	(54,'What is bothering you?','java','jsp',1,'conversation'),
    (55,'Do you guys have any big plans tonight?','java','jsp',1,'poet'),
    (56,'Has he come to get you yet?','java','jsp',1,'importance'),
    (57,'What toy do you wish you had?','java','jsp',1,'cancer'),
    (58,'Just how big an idiot do you think I am?','java','jsp',1,'reaction'),
    (59,'What is your favorite color?','java','jsp',1,'variation'),
	(60,'Who do they believe you are?','java','servlet',1,'cheek'),
	(61,'May I have some water?','java','servlet',1,'tension'),
	(62,'Can you come over now?','java','servlet',1,'engineering'),
	(63,'Could you spell it?','java','servlet',1,'farmer'),
	(64,'Have you got a match?','java','servlet',1,'virus'),
	(65,'Is that it?','java','servlet',1,'contract'),
	(66,'Why not?','java','servlet',1,'impression'),
	(67,'What do you want me to say?','java','servlet',1,'dirt'),
	(68,'Do you think this is too big?','java','servlet',1,'salad'),
	(69,'Have you spoken to him?','java','servlet',1,'procedure'),
	(70,'How do you celebrate Easter?','java','servlet',1,'bedroom'),
	(71,'Does he go to school?','java','servlet',1,'region'),
	(72,'Do you know that man with a big hat on?','java','servlet',1,'volume'),
	(73,'Would you like to have some coffee?','java','servlet',1,'chocolate'),
	(74,'It was not a big store, right?','java','servlet',1,'conversation'),
    (75,'Can I open the door?','java','servlet',1,'poet'),
    (76,'Do you like spaghetti?','java','servlet',1,'importance'),
    (77,'What did he tell you?','java','servlet',1,'cancer'),
    (78,'Are trees green or blue?','java','servlet',1,'reaction'),
    (79,'Have you ever been late a day in your life?','java','servlet',1,'variation'),
    (80,'Could you tell me what time it is?','java','servlet',1,'cheek'),
    (81,'Do you have a bigger one?','javascript','react',1,'tension'),
    (82,'What kind of music do you like to listen to?','javascript','react',1,'engineering'),
    (83,'What do you do for Thanksgiving?','javascript','react',1,'farmer'),
    (84,'What are you looking for?','javascript','react',1,'virus'),
    (85,'Why did you come?','javascript','react',1,'contract'),
    (86,'Do you have a bigger frying pan?','javascript','react',1,'impression'),
    (87,'Do you think you are a bigger man than him?','javascript','react',1,'dirt'),
	(88,'Do we know each other?','javascript','react',1,'salad'),
	(89,'Which is deeper, a lake or an ocean?','javascript','react',1,'procedure'),
	(90,'When did China become a Communist country?','javascript','react',1,'bedroom'),
	(91,'Is the door open?','javascript','react',1,'region'),
	(92,'Did you say the plant turned purple?','javascript','react',1,'volume'),
	(93,'What are your favorite foods?','javascript','react',1,'chocolate'),
	(94,'Am I in the White House?','javascript','react',1,'conversation'),
	(95,'What does your room look like?','javascript','react',1,'poet'),
	(96,'Would you like to have some coffee?','javascript','react',1,'importance'),
	(97,'Has he come to get you yet?','javascript','react',1,'cancer'),
	(98,'Could you spell it?','javascript','react',1,'reaction'),
	(99,'Where do you live?','javascript','react',1,'variation'),
	(100,'Will you be free tomorrow evening?','javascript','react',1,'cheek');
